#!/usr/bin/python
# -*- coding: utf-8 -*-
import numpy as np

info_types ={
 'AG401'            : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'AL401'            : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Cmnt_Len'         : {'cast' : int  , 'parent'    : 'table', 'shape' : 0},
 'EG401'            : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'EL401'            : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Exchange_Coeff'   : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'F_Array'          : {'cast' : np.array, 'parent' : 'table', 'shape' : ('NR', 'NT')},
 'F_Convert_Factor' : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'F_Species_Data'   : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Fmax'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Fmin'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Log_Val'          : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Material_ID'      : {'cast' : int, 'parent'      : 'table', 'shape' : 0},
 'Mean_Atomic_Mass' : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Mean_Atomic_Num'  : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Modulus'          : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'NR'               : {'cast' : int, 'parent'      : 'table', 'shape' : 0},
 'NT'               : {'cast' : int, 'parent'      : 'table', 'shape' : 0},
 'NT401'            : {'cast' : int, 'parent'      : 'table', 'shape' : 0},
 'NUM_PHASES'       : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Normal_Density'   : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'P401'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'RG401'            : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'RL401'            : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'R_Array'          : {'cast' : np.array, 'parent' : 'table', 'shape' : ('NR',)},
 'Rmax'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Rmin'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'T401'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'T_Array'          : {'cast' : np.array, 'parent' : 'table', 'shape' : ('NT',)},
 'Table_Type'       : {'cast' : int, 'parent'      : 'table', 'shape' : 0},
 'Tmax'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Tmin'             : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'X_Convert_Factor' : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'X_Species_Data'   : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Y_Convert_Factor' : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'Y_Species_Data'   : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'dFx_Species_Data' : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'dFy_Species_Data' : {'cast' : float, 'parent'    : 'table', 'shape' : 0},
 'nXYPairs'         : {'cast' : int , 'parent'     : 'table', 'shape' : 0},
}

